#include "svc_wake.h"
#include "cmd_layer.h"
#include "flash_log.h"
#include "drv_uart.h"
#include "stm32wbxx_hal.h"
#include <string.h>

/* ── Module state ─────────────────────────────────────────────────────────── */
static LIS2DW12_WakeCfg_t s_cfg   = {0};
static WakeStatus_t        s_stat  = {0};

volatile uint8_t g_wake_tx_pending = 0U;

/* ── Lifecycle ───────────────────────────────────────────────────────────── */
void SvcWake_Init(void)
{
    memset(&s_cfg,  0, sizeof(s_cfg));
    memset(&s_stat, 0, sizeof(s_stat));
    g_wake_tx_pending = 0U;
}

/* ── Config ──────────────────────────────────────────────────────────────── */
uint8_t SvcWake_SetConfig(const LIS2DW12_WakeCfg_t *cfg)
{
    if (!cfg) return CMD_ERR_PARAM;

    if (cfg->enable && !LIS2DW12_IsPowered()) {
        /* Cannot arm WoM when sensor is unpowered (conflict). */
        UART_Print("[WAKE] ERR_STATE: sensor must be powered to arm wake-on-motion\r\n");
        return CMD_ERR_STATE;
    }

    if (LIS2DW12_WakeConfigure(cfg) != HAL_OK)
        return CMD_ERR_STATE;

    memcpy(&s_cfg, cfg, sizeof(s_cfg));
    s_stat.armed = cfg->enable;
    return CMD_OK;
}

void SvcWake_GetConfig(LIS2DW12_WakeCfg_t *out)
{
    if (out) memcpy(out, &s_cfg, sizeof(*out));
}

/* ── Status ──────────────────────────────────────────────────────────────── */
void SvcWake_GetStatus(WakeStatus_t *out)
{
    if (!out) return;
    s_stat.armed          = LIS2DW12_IsWakeArmed();
    s_stat.trigger_count  = g_lis2dw12_wake_count;
    s_stat.last_trigger_ts = g_lis2dw12_wake_last_ts;
    memcpy(out, &s_stat, sizeof(*out));
}

/* ── Clear ───────────────────────────────────────────────────────────────── */
void SvcWake_Clear(void)
{
    LIS2DW12_ClearWakeIRQ();
    g_lis2dw12_wake_count   = 0U;
    g_lis2dw12_wake_last_ts = 0U;
    s_stat.trigger_count    = 0U;
    s_stat.last_trigger_ts  = 0U;
}

/* ── ISR callback ────────────────────────────────────────────────────────── */
void SvcWake_OnEvent(void)
{
    /* LIS2DW12_ClearWakeIRQ() must be called from EXTI2_IRQHandler first.   */
    s_stat.armed          = LIS2DW12_IsWakeArmed();
    s_stat.trigger_count  = g_lis2dw12_wake_count;
    s_stat.last_trigger_ts = g_lis2dw12_wake_last_ts;

    if (s_cfg.action & WAKE_ACTION_TX_BURST) {
        g_wake_tx_pending = 1U;
    }

    if (s_cfg.action & WAKE_ACTION_LOG_MARKER) {
        /* Write a marker record — LOG_MARK_TAG_WAKE (0x01). */
        FlashLogRecord_t dummy;  /* unused — FlashLog_WriteMark takes a tag byte */
        (void)dummy;
        /* Use the V2 write path if available; fall back to a no-op here.
         * The actual marker write is done via OP_LOG_MARK from cmd_layer.    */
        FlashLog_WriteMark(0x01U);   /* 0x01 = motion-triggered marker        */
    }

    /* WAKE_ACTION_WAKE_MCU: handled automatically — EXTI wakes MCU from Stop1
     * without any code here; the wakeup path is the normal interrupt return. */
}

/* ── EXTI2 IRQ handler — must be placed in a file that is linked ───────────
 * If main.c already has EXTI2_IRQHandler or it is generated by CubeMX,
 * remove this function and call LIS2DW12_ClearWakeIRQ() + SvcWake_OnEvent()
 * from the existing handler instead.                                          */
void EXTI2_IRQHandler(void)
{
    if (__HAL_GPIO_EXTI_GET_IT(GPIO_PIN_2)) {
        LIS2DW12_ClearWakeIRQ();   /* MUST be first — clears LIR latch        */
        SvcWake_OnEvent();
        HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_2);
    }
}
